### ISSUE TITLE
Scores column - rename or fix

### ISSUE THREAD

**Issue by jrosato75** [ram8647/gcb-mobilecsp#11]
The scores column for a lesson should either be renamed to something other than score, or be updated to calculate the actual score. Right now, it indicates the number of questions attempted not answered correctly. (Attempted might be a column name)

**Comment by ram8647** [comment]
Fixed (I think).   The scores column on the student-dashboard page, now displays either N/A for lessons that have no questions or where none of the questions have been attempted or a ratio such as 3/7 which means the student has gotten 3 of 7 questions correct.  The details may show that the student has not attempted some of the 7 questions in that lesson.
