### ISSUE TITLE
Teacher site link

### ISSUE THREAD

**Issue by jrosato75** [ram8647/gcb-mobilecsp#5]
Fix the message on the teach_mobilecsp teacher dashboard to give teachers a way to sign up for the dashboard.
Admins should not see the message, but should see the button to register a new teacher.

**Comment by ram8647** [comment]
The message has been changed to make it clearer that a teacher needs to register specially for the Dashboard and the link has been removed from the Teacher-facing site.  Removing the link required using the Dashboard to change the base-course.html on the teach side.
